name: "CodeQL"

on:
  push:
    branches: [master]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest


    steps:
  

    - name: ZAP Scan a
      uses: zaproxy/action-full-scan@v0.1.0
      with:
        target: 'https://public-firing-range.appspot.com'
        issue_title: 'abc'
